# Script to generate built-in skills for Rust
# Extracts skills from .md files and generates skills_data.rs

$rootDir = "D:\Projeto Fluxcodex\memoria de conversa"
$outputFile = "D:\Projeto Fluxcodex\ai-app-builder\src-tauri\src\skills_data.rs"
$skillsDir = "D:\Projeto Fluxcodex\ai-app-builder\src-tauri\resources\skills"

# Create skills resource directory
New-Item -ItemType Directory -Path $skillsDir -Force | Out-Null

function ParseSkillFile($filePath) {
    $content = Get-Content -LiteralPath $filePath -Raw -Encoding UTF8
    if ($null -eq $content -or -not $content.StartsWith('---')) {
        return $null
    }
    
    $parts = $content -split '(?m)^---\s*$', 3
    if ($parts.Count -lt 3) {
        return $null
    }
    
    $yamlBlock = $parts[1].Trim()
    $body = $parts[2].Trim()
    
    $name = ''
    $description = ''
    $priority = 5
    
    foreach ($line in $yamlBlock -split "`n") {
        if ($line -match '^name:\s*(.+)$') {
            $name = $matches[1].Trim()
        } elseif ($line -match '^description:\s*(.+)$') {
            $description = $matches[1].Trim()
        } elseif ($line -match '^priority:\s*(\d+)$') {
            $priority = [int]$matches[1]
        }
    }
    
    if ([string]::IsNullOrEmpty($name)) {
        return $null
    }
    
    return @{
        Name = $name
        Description = $description
        Content = $body
        Priority = $priority
        FilePath = $filePath
    }
}

# Collect all skill files
$files = @()

# Root directory .md files
Get-ChildItem -LiteralPath $rootDir -Filter "*.md" -File | ForEach-Object {
    $result = ParseSkillFile($_.FullName)
    if ($result) {
        $files += $result
    }
}

# Skills subdirectory - all SKILL.md files recursively
Get-ChildItem -LiteralPath "$rootDir\skills" -Recurse -Filter "SKILL.md" -File | ForEach-Object {
    $result = ParseSkillFile($_.FullName)
    if ($result) {
        $files += $result
    }
}

# Sort by name
$files = $files | Sort-Object Name

# Remove duplicates by name (keep first occurrence)
$seen = @{}
$unique = @()
foreach ($f in $files) {
    if (-not $seen.ContainsKey($f.Name)) {
        $seen[$f.Name] = $true
        $unique += $f
    }
}
$files = $unique

# Copy each skill content to resources/skills/ directory
foreach ($f in $files) {
    $resourceFile = Join-Path $skillsDir "$($f.Name).md"
    # Write the body content only (without frontmatter)
    $f.Content | Set-Content -LiteralPath $resourceFile -Encoding UTF8 -NoNewline
}

# Generate Rust code
$rustLines = [System.Collections.Generic.List[string]]::new()
$rustLines.Add('// Auto-generated by scripts/generate-builtin-skills.ps1')
$rustLines.Add('// DO NOT EDIT MANUALLY')
$rustLines.Add('')
$rustLines.Add('use crate::commands::skills::SkillMeta;')
$rustLines.Add('')
$rustLines.Add('pub fn get_builtin_skills() -> Vec<SkillMeta> {')
$rustLines.Add('    vec![')

foreach ($f in $files) {
    $descEscaped = $f.Description -replace '\\', '\\' -replace '"', '\"'
    $rustLines.Add("        SkillMeta {")
    $rustLines.Add("            name: `"$($f.Name)`".into(),")
    $rustLines.Add("            description: `"$descEscaped`".into(),")
    $rustLines.Add("            content: include_str!(`"../resources/skills/$($f.Name).md`").to_string(),")
    $rustLines.Add("            path: `"builtin://$($f.Name)`".into(),")
    $rustLines.Add("            priority: $($f.Priority),")
    $rustLines.Add("        },")
}

$rustLines.Add('    ]')
$rustLines.Add('}')

$rustCode = $rustLines -join "`n"
$rustCode | Set-Content -LiteralPath $outputFile -Encoding UTF8

Write-Output "Generated $($files.Count) built-in skills"
Write-Output "Skills data: $outputFile"
Write-Output "Skills content: $skillsDir"
